alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls -h --color=auto'
alias ll='ls -lh'
alias lal='ls -Alh'
alias startxm='startx &> $HOME/.startx/all.log'
alias dotfiles_mgmt='/usr/bin/git --git-dir=$HOME/.git_dotfiles/ --work-tree=$HOME'
alias prog_mgmt='/usr/bin/git --git-dir=/mnt/internal/ProgrammingData/.git_prog_mgmt/ --work-tree=/mnt/internal/ProgrammingData'
alias win64='env WINEPREFIX=/mnt/internal/LinuxData/wine/64/'
alias win32='env WINEARCH=win32 env WINEPREFIX=/mnt/internal/LinuxData/wine/32/'
alias gcalclim='gcalcli --configFolder=/home/tigerjack/.config/gcalcli --calendar=tigerjack89@gmail.com'
alias emt='emacsclient -t'
alias emcn='emacsclient -cn'
alias emn='emacsclient -n'
alias mutt='mutt -F ~/.config/neomutt/neomuttrc'
