# For pop up notification windows that don't use notifications api
# For specific Zoom windows
for_window [app_id="Zoom Workplace" title="^Zoom$"] border none, floating enable
for_window [app_id="Zoom Workplace" title="^About$"] border pixel, floating enable
for_window [app_id="Zoom Workplace" title="Settings"] floating enable, floating_minimum_size 960 x 700
for_window [app_id="Zoom Workplace" title="menu window"] floating enable, floating_minimum_size 960 x 700
