set nocompatible              " be iMproved, required
set encoding=utf-8
filetype off                  " required
set shell=/bin/bash

"""""
" To organize vim files as per https://tlvince.com/vim-respect-xdg
" Note that these lines should be placed BEFORE vundle section
""""
set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
if !has('nvim')
    set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
    set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
endif
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/vim/bundle/Vundle.vim

" call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
call vundle#begin('~/.config/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-speeddating'
Plugin 'Valloric/YouCompleteMe'
Plugin 'jceb/vim-orgmode'
Plugin 'bash-support.vim'
" colorscheme gruvbox
Plugin 'xolox/vim-colorscheme-switcher'
Plugin 'xolox/vim-misc'
Plugin 'rafi/awesome-vim-colorschemes'
Plugin 'chriskempson/base16-vim'
Plugin 'morhetz/gruvbox'
"/ colorscheme gruvbox

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
"""""""""""
""""
" misc
""""
set number
syntax enable

""""
" integration with kitty
""""
if $TERM == "xterm-kitty"
    set mouse=a
    try
        " undercurl support
        let &t_Cs = "\e[4:3m"
        let &t_Ce = "\e[4:0m"
    catch
    endtry
    " Change the cursor in different modes
    let &t_SI = "\e[5 q"
    let &t_SR = "\e[3 q"
    let &t_EI = "\e[1 q"
    " vim hardcodes background color erase even if the terminfo file does
    " not contain bce. This causes incorrect background rendering when
    " using a color theme with a background color.
    let &t_ut=''
    " Disable modifyOtherKeys
    let [&t_TI, &t_TE] = ['', '']
endif

""""
" colorscheme gruvbox
""""
set background=dark
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
    if exists('+termguicolors')
        let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
        let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
        set termguicolors
        autocmd vimenter * ++nested colorscheme gruvbox
        if &diff
	    colorscheme gruvbox
        endif
    else
        colorscheme gruvbox
        if &diff
            colorscheme gruvbox
        endif
    endif
endif
""""
" tabs "
""""
set tabstop=8
" Always keep softtabstop and shiftwidth to the same value
set softtabstop=4
set shiftwidth=4
" Don't expand tab, i.e. don't convert tabs to spaces
set noexpandtab
" To reload vim config file, Leader is \
nnoremap <Leader>vr :source $MYVIMRC<CR>
" To use with wayland
xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p
